package org.diplomatiq.diplomatiqbackend.repositories;

import org.diplomatiq.diplomatiqbackend.domain.entities.concretes.AuthenticationSessionMultiFactorElevationRequest;
import org.springframework.data.neo4j.repository.Neo4jRepository;

public interface AuthenticationSessionMultiFactorElevationRequestRepository extends Neo4jRepository<AuthenticationSessionMultiFactorElevationRequest, String> {
}
